//Include any predeployment steps here, such as signing up for a Marketplace AMI or making any changes to a partner account. If there are no predeployment steps, leave this file empty.

== Predeployment steps

=== Prepare an existing EKS cluster

NOTE: This step is only required if you launch this Partner Solution into an existing Amazon EKS cluster that was not created using the Amazon EKS on the AWS Cloud deployment. If you want to create a new EKS cluster with your deployment, skip to step 3.

. Sign in to your AWS account at https://aws.amazon.com with an AWS Identity and Access Management (IAM) user role that has the necessary permissions. 
. Launch the https://us-east-2.console.aws.amazon.com/cloudformation/home?region=us-east-2#/stacks/create/template?stackName=Amazon-EKS&templateURL=https://aws-quickstart.s3.us-east-1.amazonaws.com/quickstart-amazon-eks/templates/amazon-eks-entrypoint-existing-cluster.template.yaml[cluster preparation template^].
. The template launches in the US East (Ohio) Region by default. To change the Region, choose another Region from the list in the upper-right corner of the navigation bar.
. On the *Create stack* page, keep the default setting for the template URL, and then choose *Next*.
. On the *Specify stack details* page, change the stack name, if needed. Enter the name of the Amazon EKS cluster you want to deploy to, in addition to the subnet IDs and security group ID associated with the cluster. These can be obtained from the EKS cluster console.
. On the *Options* page, specify the key-value pairs for resources in your stack, and set advanced options. When you’re done, choose *Next*.
. On the *Review* page, review and confirm your template settings. Under *Capabilities*, select the two check boxes to acknowledge that the template creates IAM resources and might require the ability to automatically expand macros.
. Choose *Create stack* to deploy the stack.
. Monitor the stack’s status until it is *CREATE_COMPLETE*.
. From the *Outputs* section of the stack, note the `KubernetesRoleArn` and `HelmRoleArn` roles.
. Add the roles to the `aws-auth config` map in your cluster, specifying `system:masters` for the groups. This allows the Partner Solution to manage your cluster from AWS CloudFormation. For more information, refer to https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html[Enabling IAM principal access to your cluster^].